name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TARGET_IMAGE: 'coqorg/coq:8.16-ocaml-4.14-flambda'
      TARGET_DOC_FOLDER: master
    strategy:
      matrix:
        image:
          - 'coqorg/coq:8.16-ocaml-4.14-flambda'
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: ccyip/coqdocjs
          path: coqdocjs
          ref: 370c96d749a244b52628f93e9273868103361b8e

      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-oadt.opam'
          custom_image: ${{ matrix.image }}
          export: 'OPAMWITHDOC'
        env:
          OPAMWITHDOC: 'true'

      - name: Deploy documentation
        if: |-
          ${{
            github.event_name == 'push' &&
            matrix.image == env.TARGET_IMAGE
          }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: html
          target-folder: ${{ env.TARGET_DOC_FOLDER }}
          git-config-name: 'Qianchuan Ye'
