name: build

on:
  push:
    branches:
      - taypsi
  pull_request:
  schedule:
    # additionally run once per week (At 00:00 on Sunday) to maintain cache
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TARGET_IMAGE: 'coqorg/coq:8.16-ocaml-4.14-flambda'
      TARGET_DOC_FOLDER: taypsi
    strategy:
      matrix:
        image:
          - 'coqorg/coq:8.16-ocaml-4.14-flambda'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: ccyip/coqdocjs
          path: coqdocjs
          ref: 370c96d749a244b52628f93e9273868103361b8e

      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-taypsi.opam'
          custom_image: ${{ matrix.image }}
          before_script: |
            startGroup "Workaround permission issue"
              sudo chown -R coq:coq .
            endGroup
          script: |
            startGroup "Build project"
              opam exec -- make -j2
            endGroup
          after_script: |
            startGroup "Build documentation"
              opam exec -- make html
            endGroup
          uninstall: ''

      - name: Revert permissions
        # to avoid a warning at cleanup time
        if: ${{ always() }}
        run: sudo chown -R 1001:116 .

      - name: Deploy documentation
        if: |-
          ${{
            github.event_name == 'push' &&
            matrix.image == env.TARGET_IMAGE
          }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: html
          target-folder: ${{ env.TARGET_DOC_FOLDER }}
          git-config-name: 'Qianchuan Ye'
